version: "3"
services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    volumes:
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - RAILS_ENV=development
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
  frontend:
    build:
      context: ./client
      target: build
    ports:
      - "4200:4200"
    command: ng serve --host "0.0.0.0" --disable-host-check
    environment:
      - ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
  db:
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  traefik:
    image: traefik:v2.10.1
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock