version: "3"
services:
  api:
    depends_on:
      - db
    networks:
      - app
      - rails
  frontend:
    depends_on:
      - api
    networks:
      - app
  db:
    image: postgres:13
    networks:
      - rails
networks:
  app:
  rails:
