version: "3"
services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e test"
    volumes:
      - .:/app
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - HUB=selenium-hub
    networks:
      - app
      - rails
  frontend:
    build:
      context: ./client
    ports:
      - "4200:4200"
    command: bash -c "ng serve --host 0.0.0.0 --disable-host-check --configuration=test"
  chrome:
    image: selenium/node-chrome:4.8.1-20230306
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app
    ports:
      - "6900:5900"
  firefox:
    image: selenium/node-firefox:4.8.1-20230306
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app
    ports:
      - "6901:5900"
  selenium-hub:
    image: selenium/hub:4.8.1-20230306
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - app
  db:
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    networks:
      - rails
networks:
  app:
  rails:
