apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: rng-widgets
  annotations:
    cloud.google.com/backend-config: '{"default": "rng-backend"}'
spec:
  type: ClusterIP
  selector:
    app: rng-gke-sql-app
    tier: backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
